egz-web/src/main/java/kz/inessoft/egz/web/rest/dto/RestAnnouncementStatus.java
package kz.inessoft.egz.web.rest.dto;

import kz.inessoft.egz.dbentities.DicAnnouncementStatus;

/**
 * Created by alexey on 06.03.17.
 */
public class RestAnnouncementStatus {
    private String nameRu;

    public RestAnnouncementStatus(DicAnnouncementStatus announcementStatus) {
        nameRu = announcementStatus.getNameRu();
    }

    public String getNameRu() {
        return nameRu;
    }

    public void setNameRu(String nameRu) {
        this.nameRu = nameRu;
    }
}

egz-web/src/main/java/kz/inessoft/egz/web/jsf/files/FilesBean.java
package kz.inessoft.egz.web.jsf.files;

import kz.inessoft.egz.dbentities.TAnnouncement;
import kz.inessoft.egz.ejbapi.AnnouncementLogic;
import kz.inessoft.egz.ejbapi.DicImplementerLogic;
import kz.inessoft.egz.ejbapi.DicParticipantCompanyLogic;
import kz.inessoft.egz.ejbapi.DicPortalResourcesLogic;
import kz.inessoft.egz.ejbapi.DiscussionsLogic;
import kz.inessoft.egz.ejbapi.DocumentLogic;
import kz.inessoft.egz.ejbapi.LotLogic;
import kz.inessoft.egz.ejbapi.PortalFilesLogic;
import kz.inessoft.egz.ejbapi.TProposalsLogic;
import kz.inessoft.egz.ejbapi.ProtocolsLogic;
import kz.inessoft.egz.web.jsf.files.filesystem.*;
import kz.inessoft.egz.web.jsf.files.filesystem.IFileInfo;
import kz.inessoft.egz.web.jsf.files.filesystem.IDirectoryInfo;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIParameter;
import javax.faces.component.html.HtmlOutcomeTargetLink;
import javax.faces.component.html.HtmlOutputLink;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by alexey on 04.10.16.
 */
@ManagedBean(name = "filesBean")
@RequestScoped
public class FilesBean implements IDataLoader {
    public class DirectoryWrapper {
        private IDirectoryInfo directoryInfo;

        public DirectoryWrapper(IDirectoryInfo directoryInfo) {
            this.directoryInfo = directoryInfo;
        }

        public IDirectoryInfo getDirectoryInfo() {
            return directoryInfo;
        }

        public HtmlOutcomeTargetLink getLink() {
            return null;
        }

        public void setLink(HtmlOutcomeTargetLink link) {
            if (directoryInfo == null) return;
            if (directoryInfo.getUrlParams() != null)
                for (Map.Entry<String, Object> entry : directoryInfo.getUrlParams().entrySet()) {
                    UIParameter parameter = new UIParameter();
                    parameter.setName(entry.getKey());
                    parameter.setValue(entry.getValue());
                    link.getChildren().add(parameter);
                }
        }
    }

    public class FileWrapper {
        private IFileInfo fileInfo;

        public FileWrapper(IFileInfo fileInfo) {
            this.fileInfo = fileInfo;
        }

        public IFileInfo getFileInfo() {
            return fileInfo;
        }

        public HtmlOutputLink getLink() {
            return null;
        }

        public void setLink(HtmlOutputLink link) {
            if (fileInfo.getUrlParams() != null)
                for (Map.Entry<String, Object> entry : fileInfo.getUrlParams().entrySet()) {
                    UIParameter parameter = new UIParameter();
                    parameter.setName(entry.getKey());
                    parameter.setValue(entry.getValue());
                    link.getChildren().add(parameter);
                }
        }
    }

    @EJB
    private DocumentLogic documentLogic;

    @EJB
    private PortalFilesLogic filesLogic;

    @EJB
    private AnnouncementLogic announcementLogic;

    @EJB
    private ProtocolsLogic protocolsLogic;

    @EJB
    private TProposalsLogic TProposalsLogic;

    @EJB
    private DicImplementerLogic dicImplementerLogic;

    @EJB
    private DiscussionsLogic discussionsLogic;

    @EJB
    private LotLogic lotLogic;

    @EJB
    private DicPortalResourcesLogic portalResourcesLogic;

    @EJB
    private DicParticipantCompanyLogic dicParticipantCompanyLogic;

    private IDirectoryInfo directoryInfo;
    private TAnnouncement announcement;

    public Long getAnnouncementPortalId() {
        if (announcement == null) return null;
        return announcement.getPortalId();
    }

    public void setAnnouncementPortalId(Long portalId) {
        announcement = announcementLogic.getAnnouncementByPortalId(portalId, false);
    }

    @Override
    public DocumentLogic getDocumentLogic() {
        return documentLogic;
    }

    @Override
    public PortalFilesLogic getPortalFilesLogic() {
        return filesLogic;
    }

    @Override
    public AnnouncementLogic getAnnouncementLogic() {
        return announcementLogic;
    }

    @Override
    public ProtocolsLogic getProtocolsLogic() {
        return protocolsLogic;
    }

    public TProposalsLogic getTProposalsLogic() {
        return TProposalsLogic;
    }

    @Override
    public DicImplementerLogic getDicImplementerLogic() {
        return dicImplementerLogic;
    }

    @Override
    public DicPortalResourcesLogic getPortalResourcesLogic() {
        return portalResourcesLogic;
    }

    @Override
    public LotLogic getLotLogic() {
        return lotLogic;
    }

    @Override
    public DiscussionsLogic getDiscussionsLogic() {
        return discussionsLogic;
    }

    @Override
    public DicParticipantCompanyLogic getDicParticimantCompanyLogic() {
        return dicParticipantCompanyLogic;
    }

    public DirectoryWrapper getParentWrapper() {
        IDirectoryInfo parentDirectory = getDirectoryInfo().getParentDirectory();
        return new DirectoryWrapper(parentDirectory);
    }

    private IDirectoryInfo getDirectoryInfo() {
        if (directoryInfo == null)
            directoryInfo = new DirectoryBuilder((HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest(),
                    this, announcement).build();
        return directoryInfo;
    }

    public TAnnouncement getAnnouncement() {
        return announcement;
    }

    public List<DirectoryWrapper> getDirs() {
        ArrayList<DirectoryWrapper> retVal = new ArrayList<>();
        for (IDirectoryInfo info : getDirectoryInfo().getChildrenDirectories()) {
            retVal.add(new DirectoryWrapper(info));
        }
        return retVal;
    }

    public List<FileWrapper> getFiles() {
        ArrayList<FileWrapper> retVal = new ArrayList<>();
        for (IFileInfo info : getDirectoryInfo().getChildrenFiles()) {
            retVal.add(new FileWrapper(info));
        }
        retVal.add(new FileWrapper(new AllFilesAsZip(getAnnouncement(), getDirectoryInfo())));
        return retVal;
    }
}

egz-web/src/main/java/kz/inessoft/egz/web/jsf/search/SearchAnnouncementBean.java
package kz.inessoft.egz.web.jsf.search;

import kz.inessoft.egz.dbentities.DicAnnouncementStatus;
import kz.inessoft.egz.dbentities.DicGovOrganization;
import kz.inessoft.egz.dbentities.DicImplementer;
import kz.inessoft.egz.dbentities.TAnnouncement;
import kz.inessoft.egz.ejbapi.AnnouncementFilter;
import kz.inessoft.egz.ejbapi.AnnouncementLogic;
import kz.inessoft.egz.ejbapi.DicAnnouncementStatusLogic;
import kz.inessoft.egz.ejbapi.DicGovOrganizationLogic;
import kz.inessoft.egz.ejbapi.DicImplementerLogic;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

/**
 * Created by alexey on 25.10.16.
 */
@ManagedBean(name = "searchAnnouncementBean")
@SessionScoped
public class SearchAnnouncementBean implements Serializable {
    private static final int ROWS_PER_PAGE = 20;
    private static final int PAGES_IN_PAGER = 21;
    private AnnouncementFilter filter = new AnnouncementFilter();
    private List<TAnnouncement> announcements;
    private int totalPages;
    private int currentPage;
    private DicGovOrganization customer;
    private DicImplementer implementer;

    @EJB
    private DicAnnouncementStatusLogic announcementStatusLogic;
    private List<SelectItem> announcementStatuses;

    @EJB
    private DicGovOrganizationLogic govOrganizationLogic;

    @EJB
    private DicImplementerLogic implementerLogic;

    @EJB
    private AnnouncementLogic announcementLogic;

    public AnnouncementFilter getFilter() {
        return filter;
    }

    public List<SelectItem> getAnnouncementStatuses() {
        if (announcementStatuses == null) {
            List<DicAnnouncementStatus> statuses = announcementStatusLogic.getAnnouncementStatuses();
            announcementStatuses = new ArrayList<>();
            for (DicAnnouncementStatus status : statuses) {
                announcementStatuses.add(new SelectItem(status.getId(), status.getNameRu()));
            }
        }
        return announcementStatuses;
    }

    public void findIt() {
        currentPage = 1;
        long announcementsCount = announcementLogic.getAnnouncementsCount(filter);
        if (announcementsCount == 0) {
            totalPages = 0;
            announcements = null;
            return;
        }
        totalPages = (int) (announcementsCount / ROWS_PER_PAGE + (announcementsCount % ROWS_PER_PAGE > 0 ? 1 : 0));
        initList();
    }

    private void initList() {
        announcements = announcementLogic.findAnnouncements(filter, ROWS_PER_PAGE, (currentPage - 1) * ROWS_PER_PAGE);
    }

    public List<Integer> getPages() {
        int minPage = Integer.max(1, currentPage - (PAGES_IN_PAGER - 1)/2);
        int maxPage = Integer.min(totalPages, currentPage + (PAGES_IN_PAGER - 1)/2);
        if (maxPage - minPage != PAGES_IN_PAGER - 1) {
            if (maxPage == totalPages)
                minPage = Integer.max(1, maxPage - PAGES_IN_PAGER + 1);
            else if (minPage == 1)
                maxPage = Integer.min(totalPages, minPage + PAGES_IN_PAGER - 1);
        }
        List<Integer> retVal = new LinkedList<>();
        for (int i = minPage; i <= maxPage; i++) {
            retVal.add(i);
        }
        return retVal;
    }

    public int getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(int currentPage) {
        this.currentPage = currentPage;
        initList();
    }

    public List<TAnnouncement> getAnnouncements() {
        return announcements;
    }

    public String getCustomerName() {
        if (filter.getCustomerId() == null)
            return null;
        if (customer == null || !filter.getCustomerId().equals(customer.getId())) {
            customer = govOrganizationLogic.getById(filter.getCustomerId());
        }
        return customer.getBin() + " " + customer.getNameRu();
    }

    public String getImplementerName() {
        if (filter.getImplementerId() == null)
            return null;
        if (implementer == null || !filter.getImplementerId().equals(implementer.getId())) {
            implementer = implementerLogic.getValueById(filter.getImplementerId());
        }
        return implementer.getXin() + " " + implementer.getNameRu();
    }

    public void setSortColumn(AnnouncementFilter.ESortColumn sortColumn) {
        if (filter.getSortColumn() == null || filter.getSortColumn() != sortColumn) {
            filter.setSortColumn(sortColumn);
            filter.setAsc(true);
        } else if (filter.isAsc())
            filter.setAsc(false);
        else
            filter.setSortColumn(null);
    }

    public void sortIt() {
        initList();
    }
}

egz-web/src/main/java/kz/inessoft/egz/web/jsf/viewannounce/ViewAnnounceBean.java
package kz.inessoft.egz.web.jsf.viewannounce;

import kz.inessoft.egz.dbentities.DicParticipantCompany;
import kz.inessoft.egz.dbentities.DicParticipationTemplate;
import kz.inessoft.egz.dbentities.TAnnouncement;
import kz.inessoft.egz.dbentities.TCrossAnnouncementParticipant;
import kz.inessoft.egz.ejbapi.AnnouncementLogic;
import kz.inessoft.egz.ejbapi.AnnouncementMonitoringInfo;
import kz.inessoft.egz.ejbapi.AnnouncementSaveException;
import kz.inessoft.egz.ejbapi.DicParticipantCompanyLogic;
import kz.inessoft.egz.web.jsf.JSFFunctions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;

/**
 * Created by alexey on 05.09.16.
 */
@ManagedBean(name = "viewAnnounceBean")
@SessionScoped
public class ViewAnnounceBean implements Serializable {
    public static class Participation implements Serializable {
        private DicParticipantCompany company;
        private long templateId = 0;

        public DicParticipantCompany getCompany() {
            return company;
        }

        public void setCompany(DicParticipantCompany company) {
            this.company = company;
        }

        public long getTemplateId() {
            return templateId;
        }

        public void setTemplateId(long templateId) {
            this.templateId = templateId;
        }

        public List<SelectItem> getSelectItems() {
            List<SelectItem> retVal = new LinkedList<>();
            for (DicParticipationTemplate template : company.getTemplates()) {
                retVal.add(new SelectItem(template.getId(), template.getNameRu()));
            }
            return retVal;
        }
    }

    private static final String SAVED_TEXT = ViewAnnounceBean.class.getName() + ".SavedMonitoring";
    private static final String ERROR_TEXT = ViewAnnounceBean.class.getName() + ".Error";
    private static final Logger LOGGER = LoggerFactory.getLogger(ViewAnnounceBean.class);

    @EJB
    private AnnouncementLogic announcementLogic;

    @EJB
    private DicParticipantCompanyLogic dicParticipantCompanyLogic;

    private Long announcePortalId;
    private TAnnouncement announcement;
    private List<DicParticipantCompany> participantCompanies;
    private List<Participation> participations;

    public Long getAnnouncePortalId() {
        return announcePortalId;
    }

    public void setAnnouncePortalId(Long announcePortalId) {
        this.announcePortalId = announcePortalId;
        if (announcement != null && !announcement.getPortalId().equals(announcePortalId))
            clearCache();
    }

    private void clearCache() {
        announcement = null;
        participantCompanies = null;
        participations = null;
    }

    public TAnnouncement getAnnouncement() {
        if (announcement == null) {
            announcement = announcementLogic.getAnnouncementByPortalId(announcePortalId, true);
        }
        if (announcement == null) {
            FacesContext.getCurrentInstance().getExternalContext().setResponseStatus(404);
            FacesContext.getCurrentInstance().responseComplete();
            return null;
        } else
            return announcement;
    }

    public String getAnnouncementOriginalURL() {
        return JSFFunctions.getAnnouncementOriginalURL(announcePortalId);
    }

    private List<DicParticipantCompany> getParticipantCompanies() {
        if (participantCompanies == null) {
            participantCompanies = dicParticipantCompanyLogic.getDicParticipantCompanies();
        }
        return participantCompanies;
    }

    public List<Participation> getParticipations() {
        if (participations == null) {
            participations = new LinkedList<>();
            for (DicParticipantCompany company : getParticipantCompanies()) {
                Participation participation = new Participation();
                participation.setCompany(company);
                for (TCrossAnnouncementParticipant announcementParticipant : getAnnouncement().getCrossAnnouncementParticipants()) {
                    if (announcementParticipant.getId().getDicParticipantCompany().equals(company))
                        participation.setTemplateId(announcementParticipant.getDicParticipationTemplate().getId());
                }
                participations.add(participation);
            }
        }
        return participations;
    }

    public void saveMonitoringInfo() {
        AnnouncementMonitoringInfo monitoringInfo = new AnnouncementMonitoringInfo();
        monitoringInfo.setAnnoucementId(announcement.getId());
        monitoringInfo.setMonitorIt(announcement.isMonitoring());
        for (Participation participation : getParticipations()) {
            if (participation.getTemplateId() != 0)
                monitoringInfo.getParticipations().add(new AnnouncementMonitoringInfo.Participation(participation.getCompany().getId(), participation.getTemplateId()));
        }
        try {
            announcementLogic.setMonitoring(monitoringInfo);
        } catch (AnnouncementSaveException e) {
            LOGGER.error("Error setting announcement to monitoring", e);
            FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put(ERROR_TEXT, "При постановке объявления на мониторинг возникли проблемы. Необходим анализ лог-файлов.");
        }
        clearCache();
        String text;
        if (monitoringInfo.isMonitorIt())
            text = "Объявление успешно поставлено на мониторинг.";
        else
            text = "Объявление успешно снято с мониторинга";
        FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put(SAVED_TEXT, text);
    }

    public String getMonitoringStatus() {
        return (String) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get(SAVED_TEXT);
    }

    public String getErrorMsg() {
        return (String) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get(ERROR_TEXT);
    }
}

egz-web/src/main/webapp/files.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:c="http://java.sun.com/jsp/jstl/core"
        template="/WEB-INF/templates/main.xhtml">
    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="#{jsfParams.announcePortalId}" value="#{filesBean.announcementPortalId}"/>
        </f:metadata>

        <table id='filesList'>
            <thead>
            <tr>
                <th class='loc' colspan='2'><h:outputText value="Заявка  - #{filesBean.announcement.number}"/></th>
            </tr>
            <tr>
                <th class='label offset'>Имя</th>
                <th class='label'>Размер</th>
            </tr>
            </thead>
            <tbody>
            <ui:fragment rendered="#{filesBean.parentWrapper.directoryInfo ne null}">
                <tr>
                    <td>
                        <h:link styleClass="icon up" outcome="files" value="[..]" binding="#{filesBean.parentWrapper.link}">
                            <f:param name="#{jsfParams.htmlType}" value="#{filesBean.parentWrapper.directoryInfo.directoryType}"/>
                            <f:param name="#{jsfParams.announcePortalId}" value="#{filesBean.announcementPortalId}"/>
                        </h:link>
                    </td>
                    <td>--</td>
                </tr>
            </ui:fragment>
            <c:forEach items="#{filesBean.dirs}" var="dir">
                <tr>
                    <td>
                        <h:link styleClass="icon dir" outcome="files" value="#{dir.directoryInfo.name}" binding="#{dir.link}">
                            <f:param name="#{jsfParams.htmlType}" value="#{dir.directoryInfo.directoryType}"/>
                            <f:param name="#{jsfParams.announcePortalId}" value="#{filesBean.announcementPortalId}"/>
                        </h:link>
                    </td>
                    <td><h:outputText value="--"/></td>
                </tr>
            </c:forEach>
            <c:forEach items="#{filesBean.files}" var="file">
                <tr>
                    <td>
                        <h:outputLink styleClass="icon file" target="#{file.fileInfo.openInNewWindow ? '_blank' : ''}"
                                      value="#{request.contextPath}/docs/download" binding="#{file.link}">
                            <h:outputText value="#{file.fileInfo.fileName}"/>
                            <f:param name="#{jsfParams.downloadType}" value="#{file.fileInfo.downloadType}"/>
                            <f:param name="#{jsfParams.announceId}" value="#{filesBean.announcement.id}"/>
                        </h:outputLink>
                    </td>
                    <td><h:outputText value="#{file.fileInfo.fileLength}"/></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </ui:define>
</ui:composition>

egz-web/src/main/webapp/loadAnnouncement.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        template="WEB-INF/templates/main.xhtml">
    <ui:define name="content">
        <h:form role="form">
            <div class="form-group">
                <h:outputLabel for="txtAnnouncementId">ID объявления на портале:</h:outputLabel>
                <h:inputText styleClass="form-control" id="txtAnnouncementId"
                             value="#{loadAnnouncement.portalId}"/>
            </div>

            <h:commandButton type="submit" class="btn btn-default btn-sm" value="Запросить"
                             action="#{loadAnnouncement.startLoad}"/>

            <ui:fragment rendered="#{loadAnnouncement.announcement ne null}">
                <div class="well" style="margin-top: 15px">
                    <ui:fragment rendered="#{loadAnnouncement.announcement ne null}">
                        Информация по выбранному тендеру уже имеется в базе данных. Последняя загрузка произведена
                        <h:outputText value="#{loadAnnouncement.announcement.loadTime}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss"/>
                        </h:outputText><br/>
                        Файлы конкурса доступны для скачивания по
                        <h:outputLink value="/docs#{loadAnnouncement.docsUrl}">
                            <h:outputText value="этому адресу"/>
                        </h:outputLink><br/>
                        <h:commandButton type="submit" class="btn btn-default btn-sm" value="Обновить данные"
                                         action="#{loadAnnouncement.refreshAnnounsement}"/>
                    </ui:fragment>
                </div>
            </ui:fragment>
        </h:form>
    </ui:define>
</ui:composition>

egz-web/src/main/webapp/viewAnnouncement.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:cmp="http://java.sun.com/jsf/composite/components"
        template="WEB-INF/templates/main.xhtml">
    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="#{jsfParams.announcePortalId}" value="#{viewAnnounceBean.announcePortalId}"/>
        </f:metadata>

        <h2><h:outputText value="Объявление № #{viewAnnounceBean.announcement.number}"/></h2>
        <h:form>
            <table class="table table-stripped">
                <tbody>
                <tr>
                    <th class="text-right">Наименование объявления:</th>
                    <td>
                        <h:outputText value="#{viewAnnounceBean.announcement.nameRu}"/>
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Статус объявления:</th>
                    <td>
                        <h:outputText value="#{viewAnnounceBean.announcement.announcementStatus.nameRu}"/>
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Дата публикации объявления:</th>
                    <td>
                        <h:outputText value="#{viewAnnounceBean.announcement.publicationDate}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss"/>
                        </h:outputText>
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Дата загрузки данных:</th>
                    <td>
                        <h:outputText value="#{viewAnnounceBean.announcement.loadTime}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss"/>
                        </h:outputText>
                    </td>
                </tr>
                <tr>
                    <th class="text-right">Мониторинг:</th>
                    <td><h:selectBooleanCheckbox value="#{viewAnnounceBean.announcement.monitoring}"/></td>
                </tr>
                <ui:repeat value="#{viewAnnounceBean.participations}" var="participation">
                    <tr>
                        <th class="text-right"><h:outputText value="Участие #{participation.company.nameRu}:"/></th>
                        <td valign="">
                            <h:selectOneRadio value="#{participation.templateId}" styleClass="radioButtons">
                                <f:selectItem itemLabel="Не участвуем" itemValue="0"/>
                                <f:selectItems value="#{participation.selectItems}"/>
                            </h:selectOneRadio>
                        </td>
                    </tr>
                </ui:repeat>
                </tbody>
            </table>
            <h:panelGroup layout="block" styleClass="alert alert-success"
                          rendered="#{viewAnnounceBean.monitoringStatus ne null}">
                <strong>Сохранено!</strong> #{viewAnnounceBean.monitoringStatus}
            </h:panelGroup>
            <h:panelGroup layout="block" styleClass="alert alert-danger"
                          rendered="#{viewAnnounceBean.errorMsg ne null}">
                <strong>Ошибка!</strong> #{viewAnnounceBean.errorMsg}
            </h:panelGroup>
            <div class="btn-group">
                <h:commandButton value="Сохранить" styleClass="btn btn-primary"
                                 action="#{viewAnnounceBean.saveMonitoringInfo}"/>
            </div>
        </h:form><br/>
        <div class="well">
            Загруженные документы по конкурсу находятся по
            <h:link target="_blank" outcome="files" value="этой ссылке">
                <f:param name="#{jsfParams.announcePortalId}" value="#{viewAnnounceBean.announcePortalId}"/>
            </h:link>.<br/>
            Для просмотра оригинального объявления пройдите по <a target="_blank"
                                                                  href="#{viewAnnounceBean.announcementOriginalURL}">этой ссылке</a>
        </div>

        <h3>Лоты</h3>
        <table class="table">
            <thead>
            <tr>
                <th>Номер лота</th>
                <th>Заказчик</th>
                <th>Вид работ по классификатору ТРУ</th>
                <th>Дополнительная характеристика</th>
                <th>Плановая сумма</th>
                <th>Статус лота</th>
            </tr>
            </thead>
            <tbody>
            <ui:repeat value="#{viewAnnounceBean.announcement.lotCrossAnnouncements}" var="lot">
                <tr>
                    <td>
                        <h:outputText value="#{lot.lotNumber}"/>
                    </td>
                    <td>
                        <h:outputText value="#{lot.id.lot.customer.nameRu}"/>
                    </td>
                    <td>
                        <h:outputText value="#{lot.id.lot.dicTru.nameRu}"/>
                    </td>
                    <td>
                        <h:outputText value="#{lot.id.lot.additionalCharacteristicRu}"/>
                    </td>
                    <td align="right">
                        <cmp:outputAmount value="#{lot.id.lot.totalSum}"/>
                    </td>
                    <td>
                        <h:outputText value="#{lot.status.nameRu}"/>
                    </td>
                </tr>
            </ui:repeat>
            </tbody>
        </table>
    </ui:define>
</ui:composition>